spring:
  application:
    name: comicstore
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/comicstore
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: true
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog.xml
application:
  client:
    rating-rest:
      base-url: https://not-really-existing-service:8080
